credentials:
  usernames:
    admin:
      email: admin@cpadashboard.com
      name: Amministratore CPA Dashboard
      password: $2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewdBPj/RK.s5uO6e
cookie:
  expiry_days: 30
  key: 40bc70b5312d48634824cdbd1bb6c307
  name: cpa_dashboard_cookie
